#cloud-config
users:
- name: core
ssh_authorized_keys:
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC73ih0/qAhbOguHN9OcHUxXAWasXr12lbU7uQlTNQjOyJzYWJuqLAZphjDWnvjk/Js2KJCa7IZMf0Wp0vR3eiprq7bQMwGksSIIG4N86/xM++n3iN5tus62SvRnaFdUkE1CZkDeyatOyacHnfzMt9F0sy4TKL/3RAsos8wHyRGy6fgnllgRlJ+3WqNJxjuUnVNjbjuHEwOW2XmuGS/1yh3AOuXXSDXkde+qCSO5VaJRyjbOyMrP3MuJW7RS4NDa5iow8j18Spm285MzWggk8zd1R1E6mExVyJROwTw2DvsMvQ7TjrBJh4QjaNnk4xtuShgHjK7Y6Xv0E6wB0vCtyn3 root@docker-virtual-machine"