INSERT INTO USER VALUES (1, 'MICH');
INSERT INTO USER VALUES (2, 'ANDRES');
INSERT INTO USER VALUES (3, 'ANGIE');
INSERT INTO USER VALUES (4, 'CAROLINA');
INSERT INTO USER VALUES (5, 'AURISTELA');